### ISSUE TITLE
Homepage Image From Config File (When Image Not located in theme)

### ISSUE THREAD

**Issue by dunhampa** [PippoRJ/hugo-refresh#15]
I am not having luck specifying a new image to display on homepage from the config file that does not live in the scheme. 

I can get the desired result but only when I save my image in the theme directory
for instance if myimage is saved here:

`<site>/themes/hugo-refresh/assets/images/myimage.png`

then the following config works:

```
  homepage:
    # option to specify the title in the homepage
    title: My Title
    # option to specify the subtitle in the homepage
    subtitle: My Subtitle
    # option to specify image in the homepage
    image: "/images/myimage.png"
```
But I tried to save my image outside of theme in static/images or static/assets/images and never could make image appear. 

Should image be ok to live outside of theme?

Thanks again for theme and support.
